"""Write configs/splits.yaml: drives -> train / val / test (about 70 / 15 / 15 by labelled duration).

    python -m avirat.io.splits                  # reads results/loader_report.csv (from `make data`)

Rules (all by complete drive, never by row):
  * A drive with at least `min_labelled_s` of ground truth (ref_valid) is labelled and can train;
    drives with less are listed as `unlabelled` and belong to no split.
  * Only drives with at least `eval_min_s` of ground truth can go to val / test: one blackout window
    needs warm-up + the longest outage + post-roll (configs: evaluate.warmup_s, outages.lengths_s,
    evaluate.post_s).
  * The MVP's validation drives (S3c, Vta16, Vfa01) stay in val and its test drives (S1, M) stay in
    test, so MVP numbers remain comparable and the committed MotionNet never trained on them.
  * Remaining labelled drives fill val, then test, up to their target share of labelled duration
    (seeded shuffle, seed from configs/default.yaml); everything else is train.
  * Drives moved from the MVP's training split into val/test are listed under
    `seen_by_mvp_motionnet`: the committed model (results/models/motionnet.pt) was trained on them,
    so it must not be scored there.
"""
from __future__ import annotations

import argparse
import os
import sys

import numpy as np
import pandas as pd
import yaml

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from src.config import load_config, load_default  # noqa: E402

TARGET = {"val": 0.15, "test": 0.15}


def make_splits(report: pd.DataFrame, fixed: dict[str, list[str]], mvp_train: list[str], seed: int,
                min_labelled_s: float = 60.0, eval_min_s: float = 450.0, slack: float = 0.03) -> dict:
    ok = report[report.status == "ok"].copy()
    lab = ok[ok.ref_valid_s >= min_labelled_s]
    dur = dict(zip(lab.drive, lab.ref_valid_s))
    evaluable = {d for d, x in dur.items() if x >= eval_min_s}
    total = sum(dur.values())
    out = {"train": [], "val": [d for d in fixed.get("val", []) if d in dur],
           "test": [d for d in fixed.get("test", []) if d in dur]}
    taken = set(out["val"]) | set(out["test"])
    pool = [d for d in sorted(dur) if d not in taken]
    np.random.default_rng(seed).shuffle(pool)
    for split in ("val", "test"):
        for d in [x for x in pool if x in evaluable]:
            have = sum(dur[x] for x in out[split]) / total
            if have >= TARGET[split]:
                break
            if have + dur[d] / total <= TARGET[split] + slack:
                out[split].append(d)
                pool.remove(d)
    out["train"] = sorted(pool)
    for k in ("val", "test"):
        out[k] = sorted(out[k])
    unl = sorted(set(report.drive) - set(dur))
    share = {k: round(sum(dur[d] for d in out[k]) / total, 3) for k in ("train", "val", "test")}
    seen = sorted(d for d in out["val"] + out["test"] if d in set(mvp_train))
    missing_fixed = sorted(set(sum(fixed.values(), [])) - set(dur))
    return {"splits": out, "unlabelled": unl, "share": share, "labelled_hours": round(total / 3600, 2),
            "seen_by_mvp_motionnet": seen, "fixed_not_labelled": missing_fixed,
            "fixed_not_evaluable": sorted(set(sum(fixed.values(), [])) & (set(dur) - evaluable))}


def write(res: dict, path: str, params: dict):
    s = res["splits"]
    lines = [
        "# Drive-level split for Avirat (generated by `python -m avirat.io.splits`; do not edit by hand).",
        "# Shares are of labelled duration (samples with aligned ground truth in data/processed/).",
        f"# Labelled total {res['labelled_hours']} h; shares train {res['share']['train']:.1%}, "
        f"val {res['share']['val']:.1%}, test {res['share']['test']:.1%} (targets ~70 / 15 / 15).",
        f"# Parameters: {params}",
        "# MVP val (S3c, Vta16, Vfa01) and test (S1, M) drives are kept in place.",
        "# seen_by_mvp_motionnet: in val/test here but in the MVP model's training set ->",
        "#   never score results/models/motionnet.pt on them.",
        "# unlabelled: no usable ground truth after synchronisation; in no split.",
        "# val/test drives each hold at least eval_min_s of ground truth (room for one 120 s blackout window).",
    ]
    body = {"train": s["train"], "val": s["val"], "test": s["test"],
            "seen_by_mvp_motionnet": res["seen_by_mvp_motionnet"], "unlabelled": res["unlabelled"]}
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n" + yaml.safe_dump(body, default_flow_style=None, sort_keys=False, width=110))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--report", default="results/loader_report.csv")
    ap.add_argument("--out", default="configs/splits.yaml")
    ap.add_argument("--min-labelled-s", type=float, default=60.0)
    a = ap.parse_args(argv)
    cfg = load_default()
    mvp = load_config(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "configs", "base.yaml"))["split"]
    rep = pd.read_csv(a.report)
    eval_min = cfg["evaluate"]["warmup_s"] + max(cfg["outages"]["lengths_s"]) + cfg["evaluate"]["post_s"]
    res = make_splits(rep, {"val": mvp["val"], "test": mvp["test"]}, mvp["train"], int(cfg["seed"]),
                      a.min_labelled_s, eval_min)
    params = {"seed": int(cfg["seed"]), "min_labelled_s": a.min_labelled_s, "eval_min_s": eval_min}
    write(res, a.out, params)
    sp = res["splits"]
    print(f"{a.out}: train {len(sp['train'])} / val {len(sp['val'])} / test {len(sp['test'])} drives, "
          f"shares {res['share']}, {len(res['unlabelled'])} unlabelled; seen by MVP model: {res['seen_by_mvp_motionnet']}")
    if res["fixed_not_evaluable"]:
        print(f"  WARNING: MVP val/test drives too short for a blackout window: {res['fixed_not_evaluable']}")
    if res["fixed_not_labelled"]:
        print(f"  WARNING: MVP val/test drives without labels here: {res['fixed_not_labelled']}")


if __name__ == "__main__":
    main()
